/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicManagerUnlockRouteImport } from './routes/api/public/manager/unlock'
import { Route as ApiPublicManagerSessionRouteImport } from './routes/api/public/manager/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManagerUnlockRoute = ApiPublicManagerUnlockRouteImport.update({
  id: '/api/public/manager/unlock',
  path: '/api/public/manager/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicManagerSessionRoute = ApiPublicManagerSessionRouteImport.update({
  id: '/api/public/manager/session',
  path: '/api/public/manager/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/manager/session': typeof ApiPublicManagerSessionRoute
  '/api/public/manager/unlock': typeof ApiPublicManagerUnlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/manager/session': typeof ApiPublicManagerSessionRoute
  '/api/public/manager/unlock': typeof ApiPublicManagerUnlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/manager/session': typeof ApiPublicManagerSessionRoute
  '/api/public/manager/unlock': typeof ApiPublicManagerUnlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/manager/session' | '/api/public/manager/unlock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/manager/session' | '/api/public/manager/unlock'
  id:
    | '__root__'
    | '/'
    | '/api/public/manager/session'
    | '/api/public/manager/unlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicManagerSessionRoute: typeof ApiPublicManagerSessionRoute
  ApiPublicManagerUnlockRoute: typeof ApiPublicManagerUnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manager/unlock': {
      id: '/api/public/manager/unlock'
      path: '/api/public/manager/unlock'
      fullPath: '/api/public/manager/unlock'
      preLoaderRoute: typeof ApiPublicManagerUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manager/session': {
      id: '/api/public/manager/session'
      path: '/api/public/manager/session'
      fullPath: '/api/public/manager/session'
      preLoaderRoute: typeof ApiPublicManagerSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicManagerSessionRoute: ApiPublicManagerSessionRoute,
  ApiPublicManagerUnlockRoute: ApiPublicManagerUnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
